# Generated by Django 5.1 on 2024-10-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_image_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
    ]
